spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/ming
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

ming:
  job:
    fail: true