spring:
  jpa:
    hibernate:
      naming: # 예제의 스키마는 관습적으로 사용하는 언더스코어 표기법 대신 카멜을 사용했기 때문에 하이버네이트에 정확한 네이밍 전략 지정
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/ming
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
ming:
  job:
    fail: true
logging:
  level:
    org.springframework.batch: trace